//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by CDex.rc
//
#define ID_ERRORLOG_INIT                3
#define ID_ERRORLOG_SEARCH              4
#define ID_ERRORLOG_PRINTERRORS         5
#define ID_ERRORLOG_DISKLOG             6
#define ID_ERRORLOG_PRINTSESSIONS       7
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_WAVFILEDLG                  101
#define IDS_SAVE_FILE_AS                102
#define IDS_OPEN_FILE                   103
#define IDR_HTML_CDEXCONFIGDLG          104
#define IDD_MP3TORIFFWAV                134
#define IDD_CDDBDIALOG                  135
#define IDB_CDPLAYTOOLBAR_H             135
#define IDD_CDDBMATCH                   136
#define IDB_CDPLAYTOOLBAR_C             136
#define IDB_CDPLAYTOOLBAR_D             137
#define IDD_ENCODERWINCODECMP3DLG       138
#define IDD_ENCODERLAMEDLLDLG           139
#define IDD_ENCODERDOSDLG               141
#define IDD_DROPASK                     144
#define IDD_FILENAMEINFO                147
#define IDD_CDDBMAILTO                  148
#define IDD_RIPSTATUS                   150
#define IDD_FILECOMPARE                 151
#define IDD_PLAYFLES                    152
#define IDD_MODIFYID3                   156
#define IDD_SUBMITOPTS                  160
#define IDD_CDRDAO                      167
#define IDD_MPEGTOWAVSETTINGS           168
#define IDD_ENCODERDOSMPPDLG            169
#define IDD_CONFIG_WINAMP_INPLUGIN      170
#define IDD_EDIT_GENRES                 172
#define IDD_FILEOVERWRITE               174
#define IDD_SAVEPROFILE                 175
#define IDB_VOLUME                      179
#define IDD_CREATECUESHEET              183
#define IDD_CONFIGDLG                   184
#define IDD_ERRORLOG                    574
#define IDD_ERRORSTACK                  590
#define IDR_ERRORSTACK_VIEW             591
#define IDI_FILE_ICON                   609
#define IDD_OPEN_FILE                   611
#define IDC_LIST_REQUESTED_FILES        616
#define IDB_FILEPLAYTOOLBAR_H           700
#define IDB_FILEPLAYTOOLBAR_C           701
#define IDB_FILEPLAYTOOLBAR_D           702
#define IDC_GET_TRACKS2MP3              1002
#define IDC_GENRE                       1002
#define ID_STATIC                       1003
#define IDC_GET_TRACK2WAV               1004
#define IDC_CDDBMAIL                    1004
#define IDC_PARTCOPY                    1005
#define IDC_EDIT_DIR                    1005
#define IDC_CONFIG                      1006
#define IDC_CDEXLOGO                    1006
#define IDC_RECURSIVE_DIR               1006
#define IDC_STARTOFFSET                 1007
#define IDC_SELECT_ALL                  1007
#define IDC_ENDOFFSET                   1008
#define IDC_FILE_OPEN                   1008
#define IDC_TRACKLIST                   1009
#define IDC_DELETE_ORIGINAL             1009
#define IDC_WAV2MP3                     1010
#define IDC_RECORDCTRL                  1011
#define IDC_SYSINFO                     1011
#define IDC_PROGRESS                    1011
#define IDC_JITTERCTRL                  1012
#define IDC_PROCESSFILENAME             1012
#define IDC_BITRATE                     1013
#define IDC_OUTPUT                      1014
#define IDC_MAXBITRATE                  1014
#define IDC_MAXBITRATE2                 1015
#define IDC_MODE                        1015
#define IDC_PREVIEW                     1015
#define IDC_CURRENTFILECTRL             1016
#define IDC_CURACTION                   1016
#define IDC_MP3OUDIR                    1017
#define IDC_CNVOUTDIR                   1018
#define IDC_ABORT                       1019
#define IDC_CDROMLIST                   1020
#define IDC_READSIZE                    1021
#define IDC_READOVERLAP                 1022
#define IDC_BLOCKCOMPARE                1023
#define IDC_CHANNELSELECTION            1024
#define IDC_READRETRIES                 1024
#define IDC_RADIO2                      1025
#define IDC_INFO1                       1026
#define IDC_RADIO4                      1026
#define IDC_SPIN1                       1026
#define IDC_INFO2                       1027
#define IDC_RADIO5                      1027
#define IDC_SPIN2                       1027
#define IDC_INFO3                       1028
#define IDC_CODECS                      1028
#define IDC_CDSPEED                     1028
#define IDC_SPIN3                       1028
#define IDC_INFO4                       1029
#define IDC_CODECOPTIONS                1029
#define IDC_SPINUPTIME                  1029
#define IDC_SPIN4                       1029
#define IDC_SELCODEC                    1030
#define IDC_MATCHLIST                   1030
#define IDC_INFO5                       1030
#define IDC_SELEXTENC                   1031
#define IDC_DISCID                      1032
#define IDC_EXTENC                      1032
#define IDC_RTENCODING                  1033
#define IDC_VOLID                       1033
#define IDC_OSVERSION                   1034
#define IDC_PROGINFO                    1034
#define IDC_ENCTYPE                     1034
#define IDC_ACOUSTICMODEL               1035
#define IDC_ASPIVERSION                 1035
#define IDC_EMPHASIS                    1036
#define IDC_DRIVELETTER                 1037
#define IDC_ENCTYPE1                    1037
#define IDC_ASPIVERSION1                1037
#define IDC_CATEGORY                    1038
#define psh15                           0x040e
#define IDC_EXTENCOPTS                  1038
#define IDC_ARTIST                      1039
#define IDC_LAYER                       1039
#define IDC_VERSION                     1039
#define IDC_PEAKVALUE                   1040
#define IDC_TITLE                       1040
#define chx1                            0x0410
#define IDC_LAYER1                      1040
#define IDC_ALBUM                       1040
#define IDC_VERSION1                    1040
#define IDC_NORMTRACK                   1041
#define IDC_EXTENCTYPE                  1041
#define IDC_COMMENT                     1041
#define IDC_CODEPAGESELECTION           1041
#define IDC_CDEXVERSION                 1042
#define IDC_RADIO3                      1042
#define IDC_MP3TYPE                     1042
#define IDC_TITLE1                      1042
#define IDC_FILENAME                    1043
#define IDC_RADIO6                      1043
#define IDC_ENCODEDBY                   1043
#define IDC_RADIO1                      1044
#define IDC_QUALITY                     1044
#define IDC_CBRORVBR                    1044
#define IDC_CHANNELS                    1044
#define IDC_SUBMITVIA                   1044
#define IDC_ID3VERSION                  1044
#define IDC_WINCODEC                    1045
#define IDC_HIGHQ                       1045
#define IDC_RADIO7                      1045
#define IDC_WINCODECFORMAT              1046
#define IDC_LOWQ                        1046
#define IDC_STARTM                      1048
#define IDC_ENCOPTS                     1048
#define IDC_STARTS                      1050
#define IDC_STARTF                      1051
#define IDC_VQFMODE                     1051
#define IDC_ENDM                        1052
#define IDC_PROTOCL                     1052
#define IDC_OUTPUTTYPE                  1053
#define IDC_PROTOCOLHTTP                1053
#define IDC_USEPROXY                    1054
#define IDC_ENDS                        1055
#define IDC_PROXYADDRESS                1055
#define IDC_SPINSM                      1056
#define IDC_PROXYPORT                   1056
#define IDC_USEAUTHENTICATION           1057
#define IDC_ASPIPOSTING                 1057
#define IDC_CDEXHYPERLINK               1057
#define IDC_SPINSS                      1058
#define IDC_PROXYPASSWORD               1058
#define IDC_SPINSF                      1059
#define IDC_PROXYUSER                   1059
#define IDC_THREADPRIORITY              1059
#define IDC_SPINEM                      1060
#define IDC_TIMEOUT                     1060
#define IDC_QUERYSITES                  1061
#define IDC_SPINES                      1062
#define IDC_ENCODERSEL                  1062
#define IDC_ADDSITE                     1062
#define IDC_ENDF                        1063
#define IDC_PRIVATE                     1063
#define IDC_SPINEF                      1064
#define IDC_CRC                         1064
#define IDC_ORIGINAL                    1065
#define IDC_ENDSEC                      1066
#define IDC_COPYRIGHT                   1066
#define IDC_USEIS                       1066
#define IDC_STARTSEC                    1067
#define IDC_SEPSTRING                   1067
#define IDC_JITTERIND                   1068
#define IDC_STARTTRACK                  1069
#define IDC_JITTERIND1                  1069
#define IDC_ENDTRACK                    1070
#define IDC_JITTERIND2                  1070
#define IDC_ERRORLOG_SESSIONS           1070
#define IDC_INFO                        1071
#define IDC_NORMALIZE                   1071
#define IDC_ERRORLOG_ERRORS             1071
#define IDC_READMETHOD                  1072
#define IDC_ENCODE                      1072
#define IDC_RIFF_WAV                    1072
#define IDC_CDINFO                      1073
#define IDC_NAME3                       1073
#define IDC_NORMANDENC                  1073
#define IDC_RIPPINGMETHOD               1073
#define IDC_NAME2                       1074
#define IDC_ERRORSTACK_FRAMES           1074
#define IDC_NAME1                       1075
#define IDC_ENCODERPATH                 1075
#define ID_ERRORSTACK_PRINT             1075
#define IDC_FILEFORMAT                  1076
#define IDC_FNAMEDEMO                   1077
#define IDC_SWAPLEFTRIGHT               1078
#define IDC_FNAMEFORMATINFO             1078
#define IDC_ADDID3TAG                   1079
#define IDC_OUTFORMAT                   1079
#define IDC_PLAYLISTDEMO                1079
#define IDC_CDDBMAILBTN                 1080
#define IDC_COMPRESSION                 1080
#define IDC_PLAYLISTFORMAT              1080
#define IDC_YEAR                        1081
#define IDC_TO                          1081
#define IDC_FORMAT                      1081
#define IDC_PLAYLISTFMTINFO             1081
#define IDC_CDDBPATH                    1082
#define IDC_SUBJECT                     1082
#define IDC_JITTERERRORS                1083
#define IDC_BODYTEXT                    1083
#define IDC_WINAMPDBPATH                1083
#define IDC_PLAYSINGLE                  1084
#define IDC_FROM                        1084
#define IDC_JITTER                      1085
#define IDC_PLAYMULTI                   1085
#define IDC_AUTOCONNECT                 1085
#define IDC_STOPPLAY                    1086
#define IDC_HIQUALITY                   1086
#define IDC_USENTSCSI                   1086
#define IDC_EJECT                       1087
#define IDC_TIMEINFO                    1087
#define IDC_STAATUS                     1088
#define stc1                            0x0440
#define IDC_RIPSTATUS                   1088
#define IDC_DRIVETYPE                   1089
#define IDC_FASTREWIND                  1089
#define stc2                            0x0441
#define IDC_USEDRM                      1089
#define IDC_COPYTOCLIP                  1090
#define IDC_FASTFORWARD                 1090
#define stc3                            0x0442
#define IDC_SELFILEA                    1090
#define IDC_M3UPLAYLIST                 1091
#define IDC_PREVTRACK                   1091
#define stc4                            0x0443
#define IDC_SELFILEB                    1091
#define IDC_PLSPLAYLIST                 1092
#define IDC_DETECT                      1092
#define IDC_NEXTTRACK                   1092
#define IDC_PAUSE                       1093
#define IDC_LIST                        1093
#define IDC_GETCDDB                     1094
#define IDC_MMCSTATUS                   1094
#define IDC_COMPARE                     1094
#define IDC_SEPARATOR                   1095
#define IDC_CHARDIFFERENT               1095
#define IDC_REMOTE                      1096
#define IDC_SERVERLIST                  1097
#define IDC_FILENAMEA                   1097
#define IDC_FILENAMEB                   1098
#define IDC_CDDBTYPE                    1099
#define IDC_OFFSET                      1099
#define IDC_UNIXCDDB                    1100
#define IDC_DELETEWAV                   1100
#define IDC_FILESIZE                    1100
#define IDC_POSITION                    1100
#define IDC_OPEN                        1101
#define IDC_TRACKS2AAC                  1102
#define IDC_VOLUME                      1102
#define IDC_TRACKBUTTON                 1103
#define IDC_PLAY                        1103
#define IDC_STOP                        1104
#define IDC_UPDATETRACKLIST             1105
#define IDC_NEXT                        1105
#define IDC_RIFFWAV                     1106
#define IDC_PREV                        1106
#define IDC_RETAINWAVFILE               1107
#define IDC_NAME4                       1108
#define IDC_FILEINFO                    1108
#define IDC_SAMPLERATE                  1109
#define IDC_SHIFTLEFT                   1110
#define IDC_SHIFTRIGHT                  1111
#define IDC_EMAIL                       1112
#define IDC_VBR                         1112
#define IDC_STCDINI                     1113
#define IDC_VBRMETHOD                   1113
#define IDC_APECOMPRESSIONLEVEL         1113
#define IDC_STLOCALCDDB                 1114
#define IDC_VBRSCALE                    1114
#define IDC_OUTSAMPLERATE               1114
#define IDC_TBARTIST                    1115
#define IDC_LONGDIRNAMES                1115
#define IDC_TBARTISTE                   1116
#define IDC_FILTERHIGHFREQ              1116
#define IDC_TBTITLE                     1117
#define IDC_SIMPLESTEREO                1117
#define IDC_TBTITLEE                    1118
#define IDC_DOWNMIX                     1118
#define IDC_BROWSE                      1118
#define IDC_NORMVALUE                   1119
#define stc32                           0x045f
#define IDC_ENCSAMPLERATE               1119
#define IDC_EDIT1                       1119
#define IDC_RECFILENAME                 1119
#define IDC_EMAILADDRESS                1119
#define IDC_LNORMVALUE                  1119
#define IDC_SPLITCHAR                   1119
#define IDC_ABR                         1119
#define IDC_DEFAULTSERVER               1119
#define IDC_TRACKNUMBER                 1119
#define IDC_MULTIPLEREADCOUNT           1119
#define IDC_EXTENTION                   1119
#define IDC_EDIT_GENRE                  1119
#define IDC_TRACKOFFSET                 1119
#define IDC_PROFILENAME                 1119
#define IDC_DETAILEDDRIVEINFO           1119
#define IDC_UNORMLEVEL                  1120
#define lst1                            0x0460
#define IDC_SAVETAG                     1120
#define IDC_HTMLADDRESS                 1120
#define IDC_HTTPPATH                    1120
#define IDC_RPLC_1                      1121
#define IDC_LNORMLEVEL                  1121
#define lst2                            0x0461
#define IDC_SMTPSERVER                  1121
#define IDC_CDDBPORT                    1121
#define IDC_MINBITRATE                  1122
#define IDC_RPLC_2                      1122
#define IDC_HNORMVALUE                  1122
#define IDC_LOCATION                    1122
#define IDC_ON_THE_FLY                  1123
#define IDC_RPLC_3                      1123
#define IDC_MPEGVERSION                 1123
#define IDC_RPLC_4                      1124
#define IDC_HIDE_DOSBOX                 1124
#define IDC_RPLC_5                      1125
#define IDC_SENDWAVTOSTDIN              1125
#define IDC_PROFILE                     1126
#define IDC_RPLC_6                      1126
#define IDC_WRITEADIF                   1127
#define IDC_RPLC_7                      1127
#define IDC_USEMS                       1128
#define IDC_RPLC_8                      1128
#define IDC_RPLC_9                      1129
#define IDC_RPLC_10                     1130
#define IDC_RECORD                      1131
#define IDC_RECORDINGDEVICE             1133
#define IDC_FNAMEBUTTON                 1134
#define IDC_RECORDINGTIME               1135
#define cmb1                            0x0470
#define cmb2                            0x0471
#define IDC_RECORDSTATUS                1137
#define IDC_SUBMITOPTS                  1141
#define IDC_ID3COMMENT                  1142
#define IDC_ID3V2ENCODEDBY              1143
#define IDC_TAGOPTSPICTURE              1144
#define IDC_ILLEGAL_CHARS               1145
#define IDC_ID3V2ENCODEDBY3             1145
#define ID_CANCEL                       1146
#define IDC_USE_SIMD                    1147
#define IDC_USE_PSY                     1148
#define IDC_USE_LPF                     1149
#define IDC_SPLITTRACKNAME              1149
#define IDC_EJECTWHENFINISHED           1150
#define IDC_WRITE_ANCIL                 1151
#define IDC_SELECT_ALL_DEFAULT          1151
#define edt1                            0x0480
#define IDC_NO_PADDING                  1152
#define IDC_LOCKDURINGREAD              1152
#define IDC_USECDTEXT                   1153
#define IDC_RESETBUTTON                 1155
#define IDC_PROTOCOL                    1156
#define IDC_ADDRESS                     1157
#define IDC_PATH                        1158
#define IDC_DETAILS                     1161
#define IDC_EXPAND                      1164
#define IDC_UPDATE                      1166
#define IDC_ID3V1                       1167
#define IDC_ID3V2                       1168
#define IDC_TOTALTRACKS                 1169
#define IDC_CDDRIVE                     1170
#define IDC_MULTIPLEREAD                1170
#define IDC_FIRSTBLOCKONLY              1171
#define IDC_SETTINGS                    1173
#define IDC_OUTFREQ                     1174
#define IDC_ABOUT                       1177
#define IDC_CONFIGURE                   1178
#define IDC_INSERTNEW                   1180
#define IDC_EDIT_CDDBGENRE              1181
#define IDC_EDIT_ID3V1ID                1182
#define IDC_TOALL                       1185
#define IDC_TEMPDIR                     1186
#define IDC_NOTOALL                     1186
#define IDC_FILELIST                    1187
#define IDC_BUTTON1                     1188
#define IDC_CDDB_RESUBMIT               1188
#define IDC_PLAYLIST                    1189
#define IDC_CDDB_READ                   1189
#define IDC_COPYTOCLIPBOARD             1189
#define IDC_URL_TRANSLATOR              1190
#define IDC_QUALITYSETTING              1194
#define IDC_AUTOSHUTDOWN                1195
#define IDC_KEEPDIRLAYOUT               1196
#define IDC_DIGITALCDPLAYBACK           1196
#define IDC_TRACKNUMBERSETTING          1197
#define IDC_ENCODERTYPE                 1198
#define IDC_BANDWIDTH                   1199
#define IDC_ALLOWTNS                    1200
#define IDC_USELFE                      1201
#define IDC_QUALITYSETTINGSCROLL        1202
#define IDC_USEQUALITYSETTING           1203
#define IDC_APETAGFORMAT                1204
#define IDC_DOSFILES                    1205
#define IDC_CHANNELS1                   1206
#define IDC_ADDSEQUENCENUMBER           1207
#define IDC_SEQUENCESTART               1208
#define IDC_ABOUT_TRANSLATOR_INFO       1210
#define IDC_ABOUT_TRANSLATOR_URL        1211
#define ID_CLOSE                        1212
#define IDC_STATIC_AUTODETECT_MMCSTATUS 1213
#define IDC_STATIC_AUTODETECT_LISTDESCRIPTION 1214
#define IDC_STATIC_CDDBDIALOG_CURRENT_ACTION 1215
#define IDC_STATIC_CDDBDIALOG_MESSAGE   1216
#define IDC_STATIC_CDDBDIALOG_CREDITS   1217
#define IDC_STATIC_CDDBDIALOG_PREVIEW   1217
#define IDC_TITLEINFO_ARTIST            1218
#define IDC_TITLEINFO_TITLE             1219
#define IDC_TITLEINFO_GENRE             1220
#define IDC_TITLEINFO_YEAR              1221
#define IDC_TITLEINFO_TRACKOFFSET       1222
#define IDC_STATIC_CDDBREMOTE_SERVER    1223
#define IDC_STATIC_CDDBREMOTE_LOCATION  1224
#define IDC_STATIC_CDDBREMOTE_ADDRESS   1225
#define IDC_STATIC_CDDBREMOTE_PROTOCOL  1226
#define IDC_STATIC_CDDBREMOTE_EMAILADDRESS 1227
#define IDC_STATIC_CDDBREMOTE_PATH      1228
#define IDC_STATIC_CDDBREMOTE_PORT      1229
#define IDC_STATIC_CDDBREMOTE_TIMEOUT   1230
#define IDC_STATIC_CDDBREMOTE_PROXYPORT 1231
#define IDC_STATIC_CDDBREMOTE_PASSWORD  1232
#define IDC_STATIC_CDROMSETTINGS_CDROM  1233
#define IDC_STATIC_CDROMSETTINGS_READSECTORS 1234
#define IDC_STATIC_CDROMSETTINGS_OVERLAP 1235
#define IDC_STATIC_CDROMSETTINGS_STARTOFFSET 1236
#define IDC_STATIC_CDROMSETTINGS_ENDOFFSET 1237
#define IDC_STATIC_CDROMSETTINGS_CDROMTYPE 1238
#define IDC_STATIC_CDROMSETTINGS_RIPPINGMETHOD 1239
#define IDC_STATIC_CDROMSETTINGS_NUMRETRIES 1240
#define IDC_STATIC_CDROMSETTINGS_BLOCKCOMPARE 1241
#define IDC_STATIC_CDROMSETTINGS_CDSPEED 1242
#define IDC_STATIC_CDROMSETTINGS_SPINUPTIME 1243
#define IDC_STATIC_ENCAPETAB_CHANNELS   1245
#define IDC_STATIC_ENCAPETAB_COMPRESSIONLEVEL 1246
#define IDC_STATIC_ENCAPETAB_TAGFORMAT  1247
#define IDC_STATIC_ENCBLDTAB_BITRATE    1248
#define IDC_STATIC_ENCBLDTAB_CHANNELS   1249
#define IDC_STATIC_CDDB_SUBMITOPTS_SUBMITVIA 1250
#define IDC_STATIC_CDDB_SUBMITOPTS_EMAILADDRESS 1251
#define IDC_STATIC_CDDB_SUBMITOPTS_SMTPSERVERADDR 1252
#define IDC_STATIC_CDDB_SUBMITOPTS_SUBMISSIONPATH 1253
#define IDC_STATIC_RPLC_ILLEGALCHARS    1254
#define IDC_STATIC_RPLC_OTHERS          1255
#define IDC_STATIC_RPLC_SPACE           1256
#define IDC_STATIC_RIFFWAVTOMP3_PROCESSING 1257
#define IDC_STATIC_RECORDFILES_SAMPLERATE 1258
#define IDC_STATIC_RECORDFILES_RECORDINGDEVICE 1259
#define IDC_STATIC_RECORDFILES_FILENAME 1260
#define IDC_STATIC_RECORDFILES_OUTPUTTYPE 1261
#define IDC_STATIC_RECORDFILES_RECORDINGSTATUS 1262
#define IDC_STATIC_RECORDFILES_SECONDS  1263
#define IDC_STATIC_PCOPY_FILEPROPS      1264
#define IDC_STATIC_RECORDFILES_FILEDIRECTORY 1264
#define IDC_STATIC_PCOPY_OUTPUTTYPE     1265
#define IDC_STATIC_PCOPY_RANGESEL       1266
#define IDC_STATIC_PCOPY_STARTPOS       1267
#define IDC_STATIC_PCOPY_STOPPOS        1268
#define IDC_STATIC_PCOPY_TRACK          1269
#define IDC_STATIC_PCOPY_MINUTE         1270
#define IDC_STATIC_PCOPY_SECONDS        1271
#define IDC_STATIC_PCOPY_FRAME          1272
#define IDC_STATIC_OPENFILES_DIRECTORY  1273
#define IDC_STATIC_OPENFILES_AVIALABLEFILES 1274
#define IDC_STATIC_MPEGTOWAV_PROCESSING 1275
#define IDC_STATIC_MPEGTORIFFWAV_PROCESSING 1276
#define IDC_STATIC_LOCALCDDB_SETTINGS   1277
#define IDC_STATIC_LOCALCDDB_CDDBPATH   1278
#define IDC_STATIC_LOCALCDDB_WINAMPDB   1279
#define IDC_STATIC_GENINFO_CDDBID       1280
#define IDC_STATIC_GENINFO_ASPIMANAGER  1281
#define IDC_STATIC_GENINFO_VOLDID       1282
#define IDC_STATIC_GENINFO_OSVERSION    1283
#define IDC_STATIC_GENINFO_SCSIINFO     1284
#define IDC_STATIC_GENINFO_DRIVETYPES   1285
#define IDC_STATIC_GENERAL_TEMPDIR      1286
#define IDC_STATIC_GENERAL_FILETAGOPTIONS 1287
#define IDC_STATIC_GENERAL_ID3VERSION   1288
#define IDC_STATIC_GENERAL_TRACKNUMBER  1289
#define IDC_STATIC_GENERAL_COMMENTFIELD 1290
#define IDC_STATIC_GENERAL_ENCODEDBYFIELD 1291
#define IDC_STATIC_GENERAL_NORMALIZEVOL 1292
#define IDC_STATIC_TAGOPTIONS_PICTURETEXT 1292
#define IDC_STATIC_GENERAL_TO           1293
#define IDC_STATIC_TAGOPTIONS_Picture   1293
#define IDC_STATIC_GENERAL__TO          1294
#define IDC_STATIC_GENERAL_IFSIGNALLT   1295
#define IDC_STATIC_GENERAL_SIGNALGT     1296
#define IDC_MYNO                        1297
#define IDC_YES                         1298
#define IDC_STATIC_FILEOVERWRITE_FOLLINE 1299
#define IDC_STATIC_FILEOVERWRITE_DOESEXIST 1300
#define IDC_STATIC_FILENAMEINFO_INFO    1301
#define IDC_STATIC_FILENAMEINFO_EXAMPLES 1302
#define IDC_STATIC_FILENAMEINFO_INDENTIFIERS 1303
#define IDC_STATIC_FILENAMEINFO_BACKSLASH 1304
#define IDC_STATIC_FILEPROP_OUTPUTDIRS  1305
#define IDC_STATIC_FILEPROP_FILEFORMAT  1306
#define IDC_STATIC_FILEPROP_FILENAME    1307
#define IDC_STATIC_FILEPROP_WAVTOMPEG   1308
#define IDC_STATIC_FILEPROP_RECORDEDTRACKS 1309
#define IDC_STATIC_FILEPROP_PLSFORMAT   1310
#define IDC_STATIC_FILEPROP_FILEFORMATPLAYLIST 1311
#define IDC_STATIC_FILEPROP_PLSFILE     1312
#define IDC_STATIC_FILEPROP_FILEFORMAT_PLSTYPE 1313
#define IDC_STATIC_COMPARE_FIRSTNAME    1314
#define IDC_STATIC_COMPARE_SECONDNAME   1315
#define IDC_STATIC_COMPARE_PROGRESS     1316
#define IDC_STATIC_FAACENCOPTS_BITRATE  1318
#define IDC_STATIC_FAACENCOPTS_PROFILE  1319
#define IDC_STATIC_FAACENCOPTS_BANDWIDTH 1320
#define IDC_STATIC_GOGOENCOPTS_VARBITRATE 1321
#define IDC_STATIC_GOGOENCOPTS_BITRATE  1322
#define IDC_STATIC_GOGOENCOPTS_MODE     1323
#define IDC_STATIC_ENCDOSDLG_ENCPATH    1324
#define IDC_STATIC_ENCDOSDLG_PARAMSTRING 1325
#define IDC_STATIC_ENCDOSDLG_BITRATE    1326
#define IDC_STATIC_ENCDOSDLG_FILEEXT    1327
#define IDC_STATIC_ENCDOSMPP_ENCPATH    1328
#define IDC_STATIC_ENCDOSMPP_PARAMSTRING 1329
#define IDC_STATIC_ENCDOSXING_PATH      1330
#define IDC_STATIC_ENCDOSXING_BITRATE   1331
#define IDC_STATIC_ENCDOSXING_VBRSCALE  1332
#define IDC_STATIC_ENCPROPPAGE_ENCOPTIONS 1333
#define IDC_STATIC_ENCPROPPAGE_THREADPRIORITY 1334
#define IDC_STATIC_ENCPROPPAGE_ENCODER  1335
#define IDC_STATIC_ENCWMA8OPTS_BITRATE  1336
#define IDC_STATIC_ENCWMA8OPTS_CHANNELS 1337
#define IDC_STATIC_ENCWINOPTS_CODEC     1338
#define IDC_STATIC_ENCWINOPTS_CODECSEL  1339
#define IDC_STATIC_ENCWAVOPTS_FORMAT    1340
#define IDC_STATIC_ENCWAVOPTS_COMPRESSION 1341
#define IDC_STATIC_ENCWAVOPTS_SAMPLERATE 1342
#define IDC_STATIC_ENCWAVOPTS_CHANNELS  1343
#define IDC_STATIC_ENCOGGOPTS_CHANNELS  1344
#define IDC_STATIC_ENCOGGOPTS_MGTBITRATE 1345
#define IDC_STATIC_ENCNTTVQFOPTS_BITRPC 1346
#define IDC_STATIC_ENCNTTVQFOPTS_CHANNELS 1347
#define IDC_STATIC_ENCMP2OPTS_VBREXP    1348
#define IDC_STATIC_ENCMP2OPTS_CHANNELS  1349
#define IDC_STATIC_ENCMP2OPTS_BITRATE   1350
#define IDC_STATIC_ENCDOSVQF_MODE       1351
#define IDC_STATIC_ENCLAMEOPS_VERSION   1351
#define IDC_STATIC_ENCDOSMPP_PATH       1352
#define IDC_STATIC_ENCLAMEOPS_BRMIN     1352
#define IDC_STATIC_ENCDOSVQF_PATH       1353
#define IDC_STATIC_ENCLAMEOPS_BRMAX     1353
#define IDC_STATIC_ENCLAMEOPS_MODE      1354
#define IDC_STATIC_ENCLAMEOPS_QUALITY   1355
#define IDC_STATIC_ENCLAMEOPS_VBRMETHOD 1356
#define IDC_STATIC_ENCLAMEOPS_ABRKBPS   1357
#define IDC_STATIC_ENCLAMEOPS_VBRQUALITY 1358
#define IDC_STATIC_ENCLAMEOPS_OUTSR     1359
#define IDC_STATIC_ENCVORBIS_MINBR      1360
#define IDC_STATIC_ENCVORBIS_NOMBR      1361
#define IDC_STATIC_ENCVORBIS_MAXBR      1362
#define IDC_RECORDINGOUTPUTDIR          1363
#define IDC_PLAYER_VOLUME_ICON          1366
#define IDC_CDDB_DLG_CAT                1367
#define IDC_CDDB_CAT_SELECTION_TEXT     1368
#define IDC_COMPRESSION_LEVEL           1369
#define IDC_CDDB_CAT_SELECTION_TEXT2    1369
#define IDC_COMPRESSIONLEVELSETTING     1370
#define IDC_ADAPTIVE_MID_SIDE           1371
#define IDC_MID_SIDE                    1372
#define IDC_CHECK1                      1372
#define IDC_CHECK2                      1373
#define IDC_EXHAUSTIVE_MODEL_SEARCH     1374
#define IDC_ID3V24                      1374
#define IDC_LIST1                       1375
#define IDC_ID3V23                      1376
#define IDC_MSGBOXTEXT                  1377
#define IDC_DETECTGAPS                  1377
#define IDC_TREE1                       1379
#define IDC_TAGOPTSPICTUREGROUP         1381
#define IDC_ADDPICTURE                  1382
#define IDC_CUESHEETFILENAME            1383
#define FILEOPENORD                     1536
#define IDD_PCOPYDIALOG                 1537
#define IDD_ENCODERPROPPAGE             1538
#define IDD_CDDBSETTINGS                1539
#define IDD_GENERICPROPPAGE             1540
#define IDD_ABOUTBOX1                   1541
#define IDC_FREELENGTH                  1600
#define IDC_FREELENGTH1                 1601
#define IDC_RECORD_CHANNELS             1602
#define IDC_RECORD_CHANNELS1            1603
#define IDD_CDEX_DIALOG                 3001
#define ID_INDICATOR_CONTROLS           3002
#define ID_INDICATOR_MISC               3003
#define IDS_PLAYSINGLEBUTTON            3004
#define IDS_PLAYMULTIBUTTON             3005
#define IDS_STOPPLAYBUTTON              3006
#define IDS_EJECTBUTTON                 3007
#define IDS_BAD_SESSION                 3008
#define IDS_APPNAME                     3009
#define IDP_SOCKETS_INIT_FAILED         3010
#define IDS_FASTFORWARDBUTTON           3011
#define IDS_FASTREWINDBUTTON            3012
#define IDS_PAUSEBUTTON                 3013
#define IDS_NEXTTRACKBUTTON             3014
#define IDS_PREVTRACKBUTTON             3015
#define IDS_GETCDDBBUTTON               3016
#define IDR_MAINFRAME                   3028
#define IDR_CDEXTYPE                    3029
#define IDD_SETTINGS                    3030
#define IDD_WAVECONV                    3031
#define IDD_TITLEINFO                   3032
#define IDD_CODECSELECTION              3033
#define IDR_RTRACK                      3034
#define IDD_CDPROPPAGE                  3035
#define IDD_COPYDIALOG                  3036
#define IDR_TITLEBAR                    3037
#define IDS_CDEXVERSION                 3038
#define IDD_GENINFO                     3039
#define IDS_NOARTIST                    3039
#define IDS_NOTITLE                     3040
#define IDS_GENRE                       3041
#define IDD_AUTODETECT                  3042
#define IDS_ALBUM                       3042
#define IDS_CDDBID                      3043
#define IDD_TRACKNAME                   3044
#define IDS_ARTIST                      3044
#define IDD_FILENAMEDLG                 3045
#define IDS_TRACKNUMBER                 3045
#define IDD_FILEOPENPREVIEW             3046
#define IDS_VOLUMEID                    3046
#define IDS_TRACKNAME                   3047
#define IDD_ENCODERBLADEDLLDLG          3048
#define IDS_TRACKNUMBERLZ               3048
#define IDS_NUMBEROFTRACKS              3049
#define IDD_ENCODERDOSVQFDLG            3050
#define IDS_NAME                        3050
#define IDD_MP3TOWAV                    3051
#define IDS_TRACK                       3051
#define IDD_ENCODERWMA8DLLDLG           3052
#define IDS_START_TIME                  3052
#define IDD_PLAYTAB_ID3                 3053
#define IDS_PLAY_TIME                   3053
#define IDD_PLAYTAB_OPTS                3054
#define IDS_SIZE                        3054
#define IDD_PLAYTAB_INFO                3055
#define IDS_STATUS                      3055
#define IDD_ENCODERDOSXINGDLG           3056
#define IDS_CDEX_VERSION                3056
#define IDD_ENCODERWAVDLG               3057
#define IDS_WRONG_ARTIST_FIELD          3057
#define IDD_ENCODERFAACDLLDLG           3058
#define IDS_WRONG_ALBUM_FIELD           3058
#define IDS_WRONG_TRACK_FIELD           3059
#define IDD_RIFFWAVTOMP3                3059
#define IDS_NO_TRACKS_SELECTED          3060
#define IDD_FILENAMEPROPPAGE            3060
#define IDS_UNABLE_COPYTO_CLIPBOARD     3061
#define IDD_RECORDFILES                 3061
#define IDS_SEEKING_TRACK               3062
#define IDD_ENCODERVORBISDLLDLG         3062
#define IDS_RIP_TRACK_TO_MPEG           3063
#define IDD_RPLC_ILLEGAL                3063
#define IDS_RIP_ENCODE_ABORT            3064
#define IDD_ENCODERGOGODLLDLG           3064
#define IDS_RIP_FINISHED_OK             3065
#define IDD_ENCODERMP2DLLDLG            3065
#define IDS_RIP_TRACK_TO_WAV            3066
#define IDD_LOCALCDDBPROPPAGE           3066
#define IDS_RIP_ABORT                   3067
#define IDD_ENCODERNTTVQFDLLDLG         3067
#define IDS_RIP_WAV_FINISHED_OK         3068
#define IDD_PLAYERVIEW                  3068
#define IDS_CANNOT_CREATE_OUTDIR        3069
#define IDD_ENCODERAPEDLLDLG            3069
#define IDS_ELAPSED_TIME                3070
#define IDD_ENCODERFLACDLLDLG           3070
#define IDS_EXTRACT_TRACK               3071
#define IDS_EXTRACT_TRACK_TITLE         3071
#define IDD_GETREMOTECDINFO             3071
#define IDS_PEAK_VALUE                  3072
#define IDD_CDEXMSGBOX                  3072
#define IDS_NUM_JITTER_ERRORS           3073
#define IDD_TAGPROPPAGE                 3073
#define IDS_CONVERTING_TRACK            3074
#define IDS_CONVERTING_TRACK_TITLE      3074
#define IDS_NORMALIZING_TRACK           3075
#define IDS_NORMALIZING_TRACK_TITLE     3075
#define IDS_DETERMINING_PEAK_VALUE      3076
#define IDS_DETERMINING_PEAK_VALUE_TITLE 3076
#define IDS_REPORT_PEAK_VALUE           3077
#define IDS_CONVERTING_TRACK_NAME       3078
#define IDS_EXTRACTING_TRACK_NUMBER     3079
#define IDS_CONVERTING_TRACK_NUMBER     3080
#define IDS_NORMALIZING_TRACK_NUMBER    3081
#define IDS_GETPEAKVALUE_TRACK_NUMBER   3082
#define IDS_PROCESSING_TRACK_NUMBER     3083
#define IDS_EXTRACT_DIALOG              3084
#define IDS_FILE_CONVERSION             3085
#define IDS_REPORT_NUM_JITTER_ERRORS    3086
#define IDS_JITTER_ERROR_MSG            3087
#define IDS_YEAR                        3088
#define IDS_DATATRACK                   3089
#define IDS_AUDIOTRACK                  3090
#define IDS_CDDBINFOINCOMPLETE          3091
#define IDS_ENTRYNOTINLOCALCDDB         3092
#define IDS_ENTRYNOTINCDPLAYERINI       3093
#define IDS_MP3TABHASCHANGED            3094
#define IDS_CANTSAVEID3TAG              3095
#define IDS_CANTLOADID3TAG              3096
#define IDS_ERROR_OPENING_INPUT_FILE    3097
#define IDS_FAILED_TO_SET_PRIVILEGE     3098
#define IDS_NORMALIZATION_FACTOR        3099
#define IDS_INVALID_EMAIL_ADDRESS       3100
#define IDS_CDDB_REMOTE_TIMEOUT         3101
#define IDS_CDDB_READWRITE_ALLOWED      3102
#define IDS_CDDB_OK_READONLY            3103
#define IDS_CDDB_NO_MATCH_FOUND         3104
#define IDS_CDDB_OK_RESPONSE            3105
#define IDS_CDDB_FOUND_MULTIPLE_EXACT_MATCHES 3106
#define IDS_CDDB_FOUND_MULTIPLE_INEXACT_MATCHES 3107
#define IDS_CDDB_ENTRY_NOT_FOUND        3108
#define IDS_CDDB_ALREADY_SHOOK_HANDS    3109
#define IDS_CDDB_DB_ENTRY_CORRUPT       3110
#define IDS_CDDB_NO_HANDSHAKE           3111
#define IDS_CDDB_INVALID_HANDSHAKE      3112
#define IDS_NO_CONNECTION_ALLOWED       3113
#define IDS_NO_CONNECTION_LOAD_TOO_HIGH 3114
#define IDS_CDDB_SERVER_ERROR           3115
#define IDS_CDDB_PROTOCOL_IS_CURRENT_LEVEL 3116
#define IDS_CDDB_ILLEGAL_PROTO_LEVEL    3117
#define IDS_CDDB_CONNECTION_FAILED_FOR_REASON 3118
#define IDS_CONVERT_BUTTON_TEXT         3119
#define IDS_MODULE_NAME                 3120
#define IDS_MODULE_INFO                 3121
#define IDS_GENRE_TABLE_NOT_FOUND       3122
#define IDS_GENRE_NAME                  3123
#define IDS_GENRE_CDDB_NAME             3124
#define IDS_GENRE_ID3V1ID               3125
#define IDS_NEW_GENRE_NAME              3126
#define IDS_UNKNOWN                     3127
#define IDS_CDDB_INVALIDSERVERRESPONSE  3128
#define IDS_FILEFORMAT_TT               3129
#define IDS_CDEX_PLAYER_VERSION         3130
#define IDS_CDDB_ERROR_SEE_MSGXBOX      3131
#define IDS_ENCODER_ERROR_CANT_LAUNCH_EXENCODER 3132
#define IDS_ENCODER_ERROR_CANT_SENDDATATO_EXENCODER 3133
#define IDS_ENCODER_ERROR_CANT_CREATEVQFSCRIPT 3134
#define IDS_LOADLIBRARY_FAILED          3135
#define IDS_ENCODER_ERROR_INVALIDINPUTSTREAM 3136
#define IDS_ENCODER_ERROR_COULDNOTOPENFILE 3137
#define IDS_ENCODER_ERROR_CANTCREATEPIPE 3138
#define IDS_ENCODER_ERROR_GGODLLNEEDSFPU 3139
#define IDS_FREEDISKSPACE               3140
#define IDS_PLAYINGTRACKPOSITION        3141
#define IDS_PCOPY_RANGE                 3142
#define IDS_ERROR_CANNOTOPENCLIPBOARD   3143
#define IDS_ERROR_CANNOTEMPTYCLIPBOARD  3144
#define IDS_CDDB_ACTION_OPENCONNECTION  3145
#define IDS_CDDB_ACTION_SENDHELLOSTRING 3146
#define IDS_CDDB_ACTION_SENDSTATS       3147
#define IDS_CDDB_ACTION_SENDPROTOLEVEL  3148
#define IDS_CDDB_ACTION_SENDQUERY       3149
#define IDS_CDDB_ACTION_STARTREMOTEQUERY 3150
#define IDS_CDDB_ACTION_GETREMOTERESPONSE 3151
#define IDS_CDDB_ERROR_UNKNOWNSMTPSERVER 3152
#define IDS_CDDB_ERROR_FAILEDTOSENDSTRING 3153
#define IDS_CDDB_ACTION_CONNECTINGTOSERVER 3154
#define IDS_CDDB_ACTION_SERVERNOTREADY  3155
#define IDS_CDDB_ACTION_SENDING         3156
#define IDS_CDDB_ACTION_SENDINGDATA     3157
#define IDS_CDDB_ACTION_SENDINGBODYTEXT 3158
#define IDS_CDDB_ERROR_NOSERVERRESPONSE 3159
#define IDS_ENCODER_AVILABLENOVERSION   3160
#define IDS_ENCODER_VERSIONALPHA        3161
#define IDS_ENCODER_VERSIONBETA         3162
#define IDS_FILEFORMAT_TT2              3163
#define IDS_ENCODER_ERROR_SAMPLERATEBITRATEMISMATCH 3163
#define IDS_ENCODER_VERSIONNOTAVAILABLE 3164
#define IDS_ENCODER_VERSIONSTRING       3165
#define IDS_ENCODER_ENGINESTRING        3166
#define IDS_ERROR_COULDNOTOPENFILE      3167
#define IDS_ERROR_FILES2SMALL2COMPARE   3168
#define IDS_FILECOMP_SECFILEOFFSET      3169
#define IDS_FILECOMP_FIRSTFILEOFFSET    3170
#define IDS_FILECOMP_NOMATCHINGBLOCK    3171
#define IDS_FILECOMP_FILESAREDIFFERENT  3172
#define IDS_FILECOMP_FILESARETHESAME    3173
#define IDS_PROPSHEET_CDEXCONFIG        3174
#define IDS_PLEASE_SELECTFOLDER         3175
#define IDS_PLEASE_SELECTLISTEDITEM     3176
#define IDS_RESTART_WARNING             3177
#define IDS_ERROR_DATATAGNOTFOUND       3178
#define IDS_ERROR_NOTARIFFWAVFILE       3179
#define IDS_ERROR_COULDNOTFINDFORMATTAG 3180
#define IDS_AUTODEFECTWARNING           3181
#define IDS_TOTALRECORDING_TIME         3182
#define IDS_OPEN_FILENAME               3183
#define IDS_OPEN_DATE                   3184
#define IDS_OPEN_PATH                   3185
#define IDS_OPEN_SIZEINMB               3186
#define IDS_OPEN_SAVEBUTTON             3187
#define IDS_FILESIZE_FIRSTANDSECOND     3188
#define IDS_STATUS_OK                   3189
#define IDS_FILECOMP_FIRSTFILENAMENOTVALID 3190
#define IDS_FILECOMP_SECONDFILENAMENOTVALID 3191
#define IDS_ENCODER_ERROR_SAMPLERATEBITRATEMISMATCH2 3192
#define IDS_ENCODER_OGGINITFAILED       3192
#define IDS_ENCODER_OGGINITFAILED2      3193
#define IDS_ENCODE_ABORT                3193
#define IDS_ENCODE_FINISHED_OK          3194
#define IDS_OPEN_TYPE                   3195
#define IDR_PLAYERFRAME                 3200
#define IDS_NOFILES_SELECTED            3201
#define IDS_AUTO                        3202
#define IDS_DEFAULT                     3203
#define IDS_INPUTISOUTPUTFILENAME       3204
#define IDS_NATIVEASPINOTSUPPORTED      3205
#define IDS_FAILEDTOLOADASPIDRIVERS     3206
#define IDS_FAILEDTOGETASPISTATUS       3207
#define IDS_LANGID                      3208
#define IDS_CDPROPPAGE                  3209
#define IDS_ENCODERPROPPAGE             3210
#define IDS_GENERICPROPPAGE             3211
#define IDS_LOCALCDDBPROPPAGE           3212
#define IDS_REMOTECDDBPROPPAGE          3213
#define IDS_FILENAMEPROPPAGE            3214
#define IDS_DDX_GFLDR_EDIT_TEXT         3215
#define IDS_DDX_GFLDR_TT_MODIFY         3216
#define IDS_EXTENCFILESELECTION         3217
#define IDS_DDX_GETFILE_SELECTFILE      3218
#define IDS_BIGENDIAN                   3219
#define IDS_LITTLEENDIAN                3220
#define IDS_NONE                        3221
#define IDS_STANDARD                    3222
#define IDS_READ                        3223
#define IDS_ATAPI                       3224
#define IDS_ENABLE                      3225
#define IDS_DENSITY                     3226
#define IDS_ENDIAN                      3227
#define IDS_RESULT                      3228
#define IDS_PASS                        3229
#define IDS_FAIL                        3230
#define IDS_ASPIFAILEDSUGGESTNATIVENTSCSI 3231
#define IDS_CHECKFORADDITIONAL_LANGUAGE_FILES 3232
#define IDS_FAILEDTOOPENFILE            3233
#define IDS_TABPROPPAGE                 3234
#define IDS_PROPPAGE_SELECT_CHILD_ITEM  3235
#define IDS_TAGPICTURECFILESELECTION    3236
#define IDS_CUESHEETFILESELECTION       3237
#define IDS_CHECKSUM                    3400
#define IDS_ISRC                        3401
#define IDS_PREGAP                      3500
#define IDW_PLAYBAR                     4000
#define IDW_RECBAR                      4001
#define IDB_RECBAR256                   4002
#define IDW_PLAYFILEBAR                 4003
#define IDW_UTILBAR                     4004
#define IDB_UTILTOOLBAR_C               4005
#define IDB_UTILTOOLBAR_D               4006
#define IDB_UTILTOOLBAR_H               4007
#define IDB_RECBAR256D                  4008
#define IDS_CDDB_ERROR_FAILED_TO_CONNECT 5001
#define IDS_CDDB_INEXACT_MATCH          5002
#define IDS_CDDB_MULTIPLE_MATCHES       5003
#define IDS_CDDBDLG_NEXT                5004
#define IDS_CDDBDLG_FINISH              5005
#define IDS_CDDB_TEXT_IS_NOT_ASCII      5006
#define IDS_CDDB_CODEPAGE_RESUBMIT_GUIDANCE 5007
#define IDS_CDDB_PREVIEW                5008
#define IDS_DETECT_GAPS                 5009
#define IDS_READ_ISRC_CAPTION           5010
#define IDS_READISRC_PLEASEWAIT         5011
#define IDS_DETECTGAPFORTRACK           5020
#define ID_CONFIGURE                    32771
#define ID_TRACKS2WAV                   32772
#define ID_TRACKS2MP3                   32773
#define ID_WAV2MP3                      32774
#define ID_PTRACKS2MP3                  32775
#define ID_SYSTEMINFO                   32781
#define ID_CONFIGCD                     32782
#define ID_EJECT                        32783
#define ID_SKIPFORWARD                  32784
#define ID_SKIPREWIND                   32785
#define ID_NEXTTRACK                    32786
#define ID_SKIPPREV                     32787
#define ID_PLAYMULTI                    32788
#define ID_PLAYTRACK                    32789
#define ID_STOPBUTTON                   32790
#define ID_PAUSE                        32791
#define ID_READLOCALCDDB                32792
#define ID_READREMOTECDDB               32793
#define ID_READCDPLAYERINI              32794
#define ID_REMOTECDDB                   32795
#define ID_VIEWPLAYBAR                  32796
#define ID_VIEWRECORDBAR                32797
#define ID_PREVTRACK                    32798
#define ID_SKIPBACK                     32799
#define IDM_TRACKRENAME                 32800
#define ID_MP3TORIFFWAV                 32802
#define ID_EDIT_COPYTRACKSTOCLIPBOARD   32803
#define ID_EDIT_RENAMETRACK             32804
#define ID_VIEWERRORLOG                 32805
#define ID_EDIT_SELECTALL               32806
#define ID_CDDB_SAVETOCDPLAYERINI       32807
#define ID_CDDB_SAVETOLOCALCDDB         32808
#define ID_MP3TOWAV                     32809
#define ID_EDIT_REFRESH                 32810
#define ID_VIEWRIPPRESULT               32811
#define ID_VIEWRIPSTATUS                32812
#define ID_COMPAREFILES                 32813
#define ID_PLAYFILES                    32814
#define ID_OPTION_CLEARSTATUS           32815
#define ID_RIFFWAVTOMP3                 32816
#define ID_TOOLS_RECORDFILES            32817
#define ID_CDDB_SUBMITTOREMOTECDDB      32818
#define ID_CDDB_READCDTEXT              32819
#define ID_OPEN                         32821
#define ID_FILEOPEN                     32822
#define ID_PREV                         32823
#define ID_NEXT                         32824
#define ID_PLAY                         32825
#define ID_STOP                         32826
#define ID_FILEOPEN2                    32826
#define ID_CDDB_BATCH_QUERY             32827
#define ID_PREV2                        32828
#define ID_NEXT2                        32829
#define ID_MPEGTOMPEG                   32830
#define ID_PLAY2                        32830
#define ID_STOP2                        32831
#define ID_TRACKNAME_MOD_FCEW           32834
#define ID_TRACKNAME_MOD_FCC            32835
#define ID_TRACKNAME_MOD_AL             32836
#define ID_TRACKNAME_MOD_AU             32837
#define ID_CONFIGURE_WIN_PLUGINS        32838
#define ID_EDIT_ADDEDITGENRES           32839
#define ID_PLAYBARPAUSE                 32840
#define ID_PLAYLIST_SAVE                32841
#define ID_PLAYLIST_CLEAR               32842
#define ID_OPTIONS_PLAYRANDOM           32843
#define ID_AYUDA_TEST                   32844
#define ID_EDIT_MODIFYTRACKNAME_EXCHANGEARTISTTRACK 32845
#define ID_CDSELBAR                     32846
#define ID_PROFILESELECTION             32847
#define ID_SAVEPROFILE                  32848
#define ID_DELETEPROFILE                32850
#define ID_CDDB_READFROMMUSICBRAINZ     32869
#define ID_TOOLS_GENERATECUESHEET       32870
#define ID_TOOLS_DETECTPRE              32871
#define ID_TOOLS_READUPC                32872
#define ID_CDDB_WINAMPDB                33000
#define ID_VIEWUTILTOOLBAR              33001
#define ID_LANGUAGE_START               39051
#define ID_LANGUAGE_1                   39052
#define ID_LANGUAGE_2                   39053
#define ID_LANGUAGE_3                   39054
#define ID_LANGUAGE_4                   39055
#define ID_LANGUAGE_5                   39056
#define ID_LANGUAGE_6                   39057
#define ID_LANGUAGE_7                   39058
#define ID_LANGUAGE_8                   39059
#define ID_LANGUAGE_9                   39060
#define ID_LANGUAGE_10                  39061
#define ID_LANGUAGE_11                  39062
#define ID_LANGUAGE_12                  39063
#define ID_LANGUAGE_13                  39065
#define ID_LANGUAGE_14                  39066
#define ID_LANGUAGE_15                  39067
#define ID_LANGUAGE_16                  39068
#define ID_LANGUAGE_17                  39069
#define ID_LANGUAGE_18                  39070
#define ID_LANGUAGE_19                  39071
#define ID_LANGUAGE_20                  39072
#define ID_LANGUAGE_21                  39073
#define ID_LANGUAGE_22                  39074
#define ID_LANGUAGE_23                  39075
#define ID_LANGUAGE_24                  39076
#define ID_LANGUAGE_25                  39077
#define ID_LANGUAGE_26                  39078
#define ID_LANGUAGE_27                  39079
#define ID_LANGUAGE_28                  39080
#define ID_LANGUAGE_29                  39081
#define ID_LANGUAGE_30                  39082
#define ID_LANGUAGE_END                 39083
#define ID_ERRORSTACK_HIDESYSTEM        40050
#define ID_ERRORSTACK_HIDEEXCEPTION     40052
#define IDC_FAAC_BANDWIDTH              65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        185
#define _APS_NEXT_COMMAND_VALUE         32873
#define _APS_NEXT_CONTROL_VALUE         1384
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
